"""End-to-end regression tests against the frozen references.

These tests run the full blackbody50 configuration (12 macro steps of
100 years, 50 basic nodes) and compare the final solution state against
``tests/expected_output/expected_blackbody50.txt``. They exercise every
physics source at once, which is why they live in a cross-cutting file
rather than a per-source mirror file. Contract clauses: frozen-reference
agreement (native and external-mesh pathways) and restart round-trip
continuity. See docs/How-to/build_tests.md for the tier system.
"""

from __future__ import annotations

import shutil
import subprocess
import sys
from pathlib import Path

import numpy as np
import pytest

from tests._json_utils import parse_expected_output, read_output, solution_entries

pytestmark = [pytest.mark.integration, pytest.mark.timeout(300)]

REPO_ROOT = Path(__file__).resolve().parent.parent
EXPECTED_BLACKBODY50 = REPO_ROOT / 'tests' / 'expected_output' / 'expected_blackbody50.txt'


def _solution_by_description(outdir):
    """Map description -> (scaling, values) for the final 1200-year output."""
    doc = read_output(outdir, 1200)
    return {
        e['description']: (float(e['scaling']), np.array([float(v) for v in e['values']]))
        for e in solution_entries(doc)
    }


def test_blackbody50_final_state_matches_frozen_reference(blackbody_full):
    """The native Adams-Williamson run reproduces the frozen 1200-year solution.

    The frozen reference is the contract for the whole solver stack:
    EOS lookups, two-phase blending, flux assembly, and CVODE stepping
    all feed the final dS/dxi profile and top-node entropy.
    """
    expected = parse_expected_output(EXPECTED_BLACKBODY50)
    actual = _solution_by_description(blackbody_full)

    # The reference must describe exactly the fields the run produces;
    # a missing or extra field means the output contract changed.
    assert {e['description'] for e in expected} == set(actual)

    for entry in expected:
        scaling, values = actual[entry['description']]
        # rtol=atol=1e-5 is the historical regression tolerance: CVODE at
        # atol=rtol=1e-8 leaves ~1e-7 solver noise, and compiler-to-compiler
        # value reordering stays well below 1e-5 on this configuration.
        assert scaling == pytest.approx(entry['scaling'], rel=1e-5)
        np.testing.assert_allclose(
            values,
            entry['values'],
            rtol=1e-5,
            atol=1e-5,
            err_msg=f'mismatch in {entry["description"]}',
        )

    # Edge content of the profile: the dS/dxi field spans all 50 basic
    # nodes and stays finite from surface to core-mantle boundary.
    dsdxi = actual['dS/dxi'][1]
    assert dsdxi.shape == (50,)
    assert np.all(np.isfinite(dsdxi))


def test_external_mesh_run_reproduces_native_aw_reference(run_spider, tmp_path):
    """A run on an externally supplied AW mesh matches the native-mesh reference.

    The external mesh file is generated by tests/generate_aw_mesh.py with
    the exact blackbody50 AW parameters, so the only difference from the
    native pathway is the mesh input route (file read + midpoint-rule
    shell masses instead of analytical integrals).
    """
    mesh_file = tmp_path / 'aw_mesh_50.dat'
    proc = subprocess.run(
        [
            sys.executable,
            str(REPO_ROOT / 'tests' / 'generate_aw_mesh.py'),
            '-n',
            '50',
            '-radius',
            '6371000.0',
            '-coresize',
            '0.55',
            '-rhos',
            '4078.95095544',
            '-beta',
            '1.1115348931000002e-07',
            '-gravity',
            '-10.0',
            '-o',
            str(mesh_file),
        ],
        capture_output=True,
        text=True,
    )
    assert proc.returncode == 0, proc.stderr
    # 1 header line + 50 basic + 49 staggered nodes.
    assert len(mesh_file.read_text().splitlines()) == 100

    outdir = run_spider(
        overrides=('-MESH_SOURCE', '1', '-mesh_external_filename', str(mesh_file)),
        name='external_mesh',
    )
    expected = parse_expected_output(EXPECTED_BLACKBODY50)
    actual = _solution_by_description(outdir)

    for entry in expected:
        scaling, values = actual[entry['description']]
        # Scalings are configuration constants and stay at the tight tolerance.
        assert scaling == pytest.approx(entry['scaling'], rel=1e-5)
        # rtol=atol=2e-3 (not 1e-5): the external-mesh pathway uses
        # midpoint-rule quadrature for shell masses, while AW uses
        # analytical integrals. For 50 nodes this gives ~2e-5
        # discretization error in dxidr that propagates through the
        # time integration.
        np.testing.assert_allclose(
            values,
            entry['values'],
            rtol=2e-3,
            atol=2e-3,
            err_msg=f'mismatch in {entry["description"]}',
        )


@pytest.mark.physics_invariant
def test_restart_from_snapshot_continues_the_run(blackbody_full, run_spider, tmp_path):
    """Restarting from the 1200-year snapshot reproduces it and keeps cooling.

    The restart pathway (-IC_INTERIOR 2) must read back the JSON the
    binary itself wrote (round-trip property) and continue the secular
    cooling trend. The macro-step counter is absolute, so continuing a
    12-step run by two steps needs -nstepsmacro 14.
    """
    # Never restart inside the cached run's directory; copy the snapshot out.
    snapshot = tmp_path / '1200.json'
    shutil.copy(blackbody_full / '1200.json', snapshot)

    outdir = run_spider(
        overrides=(
            '-IC_INTERIOR',
            '2',
            '-ic_interior_filename',
            str(snapshot),
            '-nstepsmacro',
            '14',
        ),
        name='restart',
    )

    # Round-trip identity: the re-emitted 1200-year state matches the snapshot.
    source = _solution_by_description(blackbody_full)
    restarted = _solution_by_description(outdir)
    for description, (scaling, values) in source.items():
        r_scaling, r_values = restarted[description]
        assert r_scaling == pytest.approx(scaling, rel=1e-12)
        np.testing.assert_allclose(
            r_values,
            values,
            rtol=1e-10,
            atol=1e-12,
            err_msg=f'restart did not reproduce {description}',
        )

    # Continuation: two further outputs exist and the top-node entropy
    # keeps decreasing under grey-body cooling (no internal heating in
    # this configuration).
    final = read_output(outdir, 1400)
    assert final['step'] == 14
    assert float(final['time_years']) == pytest.approx(1400.0, rel=1e-12)
    s_top_source = source['S at top staggered node'][1][0]
    s_top_final = {e['description']: float(e['values'][0]) for e in solution_entries(final)}[
        'S at top staggered node'
    ]
    assert s_top_final < s_top_source
