#!/usr/bin/env python3
"""Generate the runtime-options reference page from parameters.c.

SPIDER is configured entirely through PETSc-style options (one
``-name value`` per line in an options file, or the same flags on the
command line). ``parameters.c`` is the single place the options are
consumed, so this script extracts every literal option registration
(``PetscOptionsGet*("-name", ..., default, ...)`` together with any
same-line unit comment) and writes a markdown reference table.

Options whose names are composed at runtime from a prefix (per-phase
EOS options such as ``-melt_TYPE``, per-radionuclide options such as
``-al26_t0``, and per-volatile options) cannot be extracted statically;
the page documents those families in a hand-maintained epilogue kept in
this script.

Usage
-----
    python tools/generate_options_reference.py --out docs/Reference/options.md

The committed page is regenerated by the documentation workflow at
deploy time, so the published copy always reflects the current
parameters.c. Run this script and commit the result whenever options
are added or changed.
"""

from __future__ import annotations

import argparse
import re
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parent.parent
_PARAMETERS = _REPO_ROOT / 'parameters.c'

# PetscOptionsGetPositiveScalar("-name",&var,default,NULL)  (SPIDER helper)
_HELPER_RE = re.compile(
    r'PetscOptionsGet(?P<kind>PositiveScalar|PositiveInt)\s*\(\s*"(?P<name>-[A-Za-z0-9_]+)"'
    r'\s*,\s*[^,]+,\s*(?P<default>[^,]+),'
)
# PetscOptionsGetScalar/Int/Bool/String(NULL,NULL,"-name",...)  (PETSc API)
_PETSC_RE = re.compile(
    r'PetscOptionsGet(?P<kind>Scalar|Int|Bool|String)\s*\(\s*NULL\s*,\s*NULL\s*,'
    r'\s*"(?P<name>-[A-Za-z0-9_]+)"'
)
_COMMENT_RE = re.compile(r'//\s*(.*)$')

_KIND_LABEL = {
    'PositiveScalar': 'positive scalar',
    'PositiveInt': 'positive integer',
    'Scalar': 'scalar',
    'Int': 'integer',
    'Bool': 'flag',
    'String': 'string',
}

_HEADER = """# Runtime options

SPIDER is configured through PETSc-style options: one `-name value`
pair per line in an options file passed as
`spider -options_file <file.opts>`, with further pairs on the command
line overriding the file. All options are consumed in `parameters.c`;
this page is generated from it by `tools/generate_options_reference.py`.
All values are SI unless the description notes otherwise.

The annotated example configurations under `tests/opts/` show working
combinations: `blackbody50.opts` is the minimal grey-body cooling setup
and `reaction.opts` adds volatiles, reactions, and the coupled
atmosphere.

## Options

| Option | Type | Default | Description |
|---|---|---|---|
"""

_EPILOGUE = """
## Prefixed option families

The options below are registered with runtime-composed names, so they
appear once per phase, radionuclide, or volatile rather than as fixed
strings.

### Per-phase equation of state

`-phase_names <melt,solid>` declares the phases; each phase `<p>` then
reads its own EOS configuration: `-<p>_TYPE` (1 = lookup), the table
files `-<p>_alpha_filename`, `-<p>_cp_filename`, `-<p>_dTdPs_filename`,
`-<p>_rho_filename`, `-<p>_temp_filename` (each also available with an
`_rel_to_src` suffix to resolve relative to the source tree),
`-<p>_phase_boundary_filename`, the transport constants `-<p>_log10visc`
and `-<p>_cond`, the viscosity law parameters `-<p>_activation_energy`,
`-<p>_activation_volume`, `-<p>_visc_ref_temp`, `-<p>_visc_ref_pressure`,
`-<p>_visc_ref_comp`, and the Adams-Williamson parameters `-<p>_rhos`
and `-<p>_beta` (used with the `adamswilliamson` EOS type).

### Per-radionuclide heating

`-radionuclide_names <name,...>` declares the heat sources; each
radionuclide `<r>` reads `-<r>_t0` (years), `-<r>_abundance`
(fractional), `-<r>_concentration` (ppmw), `-<r>_heat_production`
(W/kg), and `-<r>_half_life` (years).

### Per-volatile and per-reaction chemistry

Volatile species and their reactions (used by configurations like
`tests/opts/reaction.opts`) read per-species solubility, molar mass,
initial abundance, and escape parameters under the volatile's name
prefix (for example `-H2O_initial_ppmw`), plus reaction definitions
pairing the species. The reaction test configuration documents the
working set.
"""


def extract_options(source: Path) -> list[tuple[str, str, str, str]]:
    """Extract literal option registrations from a C source file.

    Parameters
    ----------
    source : Path
        C file to scan (``parameters.c``).

    Returns
    -------
    list of tuple
        Rows of (name, type label, default, description), ordered by
        first appearance.
    """
    rows: list[tuple[str, str, str, str]] = []
    seen: set[str] = set()
    for line in source.read_text().splitlines():
        match = _HELPER_RE.search(line) or _PETSC_RE.search(line)
        if not match:
            continue
        name = match.group('name')
        if name in seen:
            continue
        seen.add(name)
        kind = _KIND_LABEL[match.group('kind')]
        default = (match.groupdict().get('default') or '').strip()
        comment_match = _COMMENT_RE.search(line)
        description = comment_match.group(1).strip() if comment_match else ''
        rows.append((name, kind, default, description))
    return rows


def render(rows: list[tuple[str, str, str, str]]) -> str:
    """Render the markdown page."""
    body = _HEADER
    for name, kind, default, description in rows:
        default_cell = f'`{default}`' if default else ''
        body += f'| `{name}` | {kind} | {default_cell} | {description} |\n'
    return body + _EPILOGUE


def main() -> int:
    """Entry point."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        '--out',
        type=Path,
        default=_REPO_ROOT / 'docs' / 'Reference' / 'options.md',
        help='Output markdown path (default: docs/Reference/options.md).',
    )
    args = parser.parse_args()

    rows = extract_options(_PARAMETERS)
    if len(rows) < 30:
        raise RuntimeError(
            f'only {len(rows)} options extracted from {_PARAMETERS}; '
            'the extraction patterns no longer match parameters.c.'
        )
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(rows))
    print(f'wrote {args.out} ({len(rows)} options)')
    return 0


if __name__ == '__main__':
    import sys

    sys.exit(main())
